package fern.nail.art.nailscheduler.telegram.model;

public enum LocalState {
    AWAITING_USERNAME,
    AWAITING_PASSWORD,
    AWAITING_REPEAT_PASSWORD,
    AWAITING_PHONE,
    AWAITING_FIRST_NAME,
    AWAITING_LAST_NAME,
    PASSWORD_ACCEPTED,
    FULL_NAME_ACCEPTED,
    SEND_USERNAME_REQUEST,
    SEND_PASSWORD_REQUEST,
    SEND_NAME_REQUEST
}
