package fern.nail.art.nailscheduler.telegram.model;

public enum LocalState {
    // AUTH
    ACCEPTED_PASSWORD,
    AWAITING_USERNAME,
    AWAITING_PASSWORD,
    AWAITING_REPEAT_PASSWORD,
    SEND_REQUEST_USERNAME,

    // SETTINGS
    AWAITING_PHONE,
    AWAITING_FIRST_NAME,
    AWAITING_LAST_NAME,
    ACCEPTED_FULL_NAME,
    ACCEPTED_PHONE,
    SEND_REQUEST_PASSWORD,
    SEND_REQUEST_NAME,

    // WORKDAY
    TEMPLATES,
    SET_TEMPLATES,
    AWAITING_EDIT_TEMPLATE,
    SPECIFICS,
    ADD_SPECIFIC_WORKDAY
}
