package fern.nail.art.nailscheduler.telegram.model;

public enum LocalState {
    AWAITING_USERNAME,
    AWAITING_PASSWORD,
    AWAITING_REPEAT_PASSWORD,
    AWAITING_PHONE,
    AWAITING_FIRST_NAME,
    AWAITING_LAST_NAME,
    ACCEPTED_PASSWORD,
    ACCEPTED_FULL_NAME,
    ACCEPTED_PHONE,
    SEND_REQUEST_USERNAME,
    SEND_REQUEST_PASSWORD,
    SEND_REQUEST_NAME
}
